INSERT INTO exercicios (nome, grupo_muscular, grupos_secundarios, descricao, equipamento, global) VALUES

-- PEITO (12 exercícios)
('Supino Reto com Barra', 'Peito', ARRAY['Tríceps', 'Ombro'], 'Deite no banco, pegue a barra na largura dos ombros, desça até o peito e empurre para cima.', 'Barra', true),
('Supino Inclinado com Barra', 'Peito', ARRAY['Tríceps', 'Ombro'], 'Banco inclinado a 30-45°, desça a barra até a parte superior do peito e empurre.', 'Barra', true),
('Supino Declinado com Barra', 'Peito', ARRAY['Tríceps'], 'Banco declinado, barra desce até a parte inferior do peito e empurre.', 'Barra', true),
('Supino Reto com Halter', 'Peito', ARRAY['Tríceps', 'Ombro'], 'Deite no banco com um halter em cada mão, desça com cotovelos a 45° e empurre.', 'Halter', true),
('Supino Inclinado com Halter', 'Peito', ARRAY['Tríceps', 'Ombro'], 'Banco inclinado, halteres na altura do peito superior, empurre para cima.', 'Halter', true),
('Crucifixo com Halter', 'Peito', ARRAY['Ombro'], 'Deite no banco, braços abertos com leve flexão no cotovelo, junte os halteres no topo.', 'Halter', true),
('Crucifixo Inclinado com Halter', 'Peito', ARRAY['Ombro'], 'Banco inclinado, abra os braços amplamente e junte os halteres contraindo o peito.', 'Halter', true),
('Crossover no Cabo', 'Peito', ARRAY['Ombro'], 'Polias altas, puxe os cabos à frente cruzando as mãos, contraindo o peito no final.', 'Cabo', true),
('Peck Deck', 'Peito', ARRAY['Ombro'], 'Sentado na máquina, junte os antebraços nas almofadas contraindo o peito.', 'Máquina', true),
('Supino no Smith', 'Peito', ARRAY['Tríceps', 'Ombro'], 'Deite no banco abaixo da barra do Smith, desça até o peito e empurre.', 'Smith', true),
('Flexão de Braço', 'Peito', ARRAY['Tríceps', 'Ombro'], 'Posição de prancha, desça o peito até quase tocar o chão e empurre.', 'Peso Corporal', true),
('Flexão com Pés Elevados', 'Peito', ARRAY['Tríceps', 'Ombro'], 'Pés em superfície elevada, execute a flexão enfatizando a parte superior do peito.', 'Peso Corporal', true),

-- COSTAS (12 exercícios)
('Puxada Frontal na Polia', 'Costas', ARRAY['Bíceps', 'Trapézio'], 'Sentado na máquina, puxe a barra até a altura do queixo contraindo a costas.', 'Máquina', true),
('Remada Curvada com Barra', 'Costas', ARRAY['Bíceps', 'Trapézio', 'Lombar'], 'Incline o tronco, puxe a barra até o abdômen mantendo as costas retas.', 'Barra', true),
('Remada Unilateral com Halter', 'Costas', ARRAY['Bíceps', 'Trapézio'], 'Apoie um joelho no banco, puxe o halter até o quadril com o cotovelo próximo ao corpo.', 'Halter', true),
('Levantamento Terra', 'Costas', ARRAY['Quadríceps', 'Glúteos', 'Lombar', 'Trapézio'], 'Pés na largura do quadril, puxe a barra do chão mantendo a coluna neutra até ficar em pé.', 'Barra', true),
('Pulldown com Cabo', 'Costas', ARRAY['Bíceps'], 'Na polia alta, puxe o cabo até a altura do peito com pegada pronada ou supinada.', 'Cabo', true),
('Remada Sentada no Cabo', 'Costas', ARRAY['Bíceps', 'Trapézio'], 'Sentado, puxe o cabo até o abdômen mantendo o tronco ereto.', 'Cabo', true),
('Barra Fixa', 'Costas', ARRAY['Bíceps', 'Trapézio'], 'Pendurado na barra, puxe o corpo até o queixo ultrapassar a barra.', 'Peso Corporal', true),
('Remada na Máquina', 'Costas', ARRAY['Bíceps', 'Trapézio'], 'Sentado na máquina, puxe as alças até o abdômen contraindo as costas.', 'Máquina', true),
('Puxada Supinada', 'Costas', ARRAY['Bíceps'], 'Na polia alta com pegada supinada, puxe até o queixo contraindo as costas.', 'Máquina', true),
('Remada com Barra T', 'Costas', ARRAY['Bíceps', 'Trapézio'], 'Barra fixada no chão, puxe até o abdômen com as mãos próximas.', 'Barra', true),
('Pullover com Halter', 'Costas', ARRAY['Peito', 'Tríceps'], 'Deite no banco, segure o halter acima do peito e desça atrás da cabeça.', 'Halter', true),
('Remada Cavalinho', 'Costas', ARRAY['Bíceps', 'Trapézio', 'Lombar'], 'Apoiado no banco, puxe os dois halteres ao mesmo tempo até o quadril.', 'Halter', true),

-- OMBRO (12 exercícios)
('Desenvolvimento com Barra', 'Ombro', ARRAY['Tríceps', 'Trapézio'], 'Em pé ou sentado, empurre a barra de frente acima da cabeça e desça até o queixo.', 'Barra', true),
('Desenvolvimento com Halter', 'Ombro', ARRAY['Tríceps', 'Trapézio'], 'Sentado, empurre os halteres acima da cabeça alternando ou simultaneamente.', 'Halter', true),
('Elevação Lateral com Halter', 'Ombro', ARRAY[], 'Em pé, levante os halteres lateralmente até a altura dos ombros com leve flexão no cotovelo.', 'Halter', true),
('Elevação Frontal com Halter', 'Ombro', ARRAY['Peito'], 'Em pé, levante um halter por vez à frente até a altura do ombro.', 'Halter', true),
('Elevação Lateral no Cabo', 'Ombro', ARRAY[], 'Polia baixa, puxe lateralmente o cabo até a altura do ombro.', 'Cabo', true),
('Desenvolvimento Arnold', 'Ombro', ARRAY['Tríceps'], 'Segure os halteres à frente com palmas para dentro, gire e empurre acima da cabeça.', 'Halter', true),
('Remada Alta com Barra', 'Ombro', ARRAY['Trapézio', 'Bíceps'], 'Pegada fechada na barra, puxe até o queixo com cotovelos para fora.', 'Barra', true),
('Face Pull no Cabo', 'Ombro', ARRAY['Trapézio'], 'Polia alta, puxe a corda até o rosto com cotovelos elevados.', 'Cabo', true),
('Desenvolvimento na Máquina', 'Ombro', ARRAY['Tríceps'], 'Sentado, empurre as alças acima da cabeça na máquina de ombro.', 'Máquina', true),
('Elevação Lateral com Elástico', 'Ombro', ARRAY[], 'Pise no elástico, puxe lateralmente até a altura dos ombros.', 'Elástico', true),
('Desenvolvimento no Smith', 'Ombro', ARRAY['Tríceps', 'Trapézio'], 'Sentado abaixo da barra do Smith, empurre acima da cabeça e desça controlado.', 'Smith', true),
('Rotação Externa com Cabo', 'Ombro', ARRAY[], 'Cotovelo dobrado a 90°, gire o antebraço para fora com o cabo na polia baixa.', 'Cabo', true),

-- BÍCEPS (10 exercícios)
('Rosca Direta com Barra', 'Bíceps', ARRAY['Antebraço'], 'Em pé, cotovelos fixos ao corpo, suba a barra até os ombros e desça controlado.', 'Barra', true),
('Rosca Alternada com Halter', 'Bíceps', ARRAY['Antebraço'], 'Em pé, suba cada halter alternadamente girando o punho (supinação).', 'Halter', true),
('Rosca Martelo', 'Bíceps', ARRAY['Antebraço', 'Braquial'], 'Segure os halteres com pegada neutra (palma para dentro) e suba alternando.', 'Halter', true),
('Rosca Scott com Barra', 'Bíceps', ARRAY[], 'Apoie os tríceps no banco Scott, suba a barra até os ombros e desça completamente.', 'Barra', true),
('Rosca Concentrada', 'Bíceps', ARRAY[], 'Sentado, apoie o cotovelo na coxa, suba o halter em direção ao ombro.', 'Halter', true),
('Rosca no Cabo', 'Bíceps', ARRAY['Antebraço'], 'Polia baixa, suba o cabo mantendo os cotovelos fixos.', 'Cabo', true),
('Rosca 21', 'Bíceps', ARRAY[], '7 repetições na metade inferior, 7 na metade superior e 7 completas com barra.', 'Barra', true),
('Rosca Inversa com Barra', 'Bíceps', ARRAY['Antebraço'], 'Pegada pronada na barra, suba mantendo os cotovelos próximos ao corpo.', 'Barra', true),
('Rosca na Máquina', 'Bíceps', ARRAY[], 'Sentado na máquina, suba as alças até os ombros de forma controlada.', 'Máquina', true),
('Rosca com Kettlebell', 'Bíceps', ARRAY['Antebraço'], 'Segure o kettlebell pela alça, execute a rosca com supinação no topo.', 'Kettlebell', true),

-- TRÍCEPS (10 exercícios)
('Tríceps Pulley', 'Tríceps', ARRAY[], 'Polia alta com corda ou barra, empurre para baixo mantendo os cotovelos fixos ao corpo.', 'Cabo', true),
('Tríceps Testa com Barra', 'Tríceps', ARRAY[], 'Deite no banco, desça a barra até a testa dobrando os cotovelos e empurre.', 'Barra', true),
('Supino Fechado', 'Tríceps', ARRAY['Peito', 'Ombro'], 'Pegada fechada na barra (mãos juntas), empurre controlando os cotovelos.', 'Barra', true),
('Tríceps Francês com Halter', 'Tríceps', ARRAY[], 'Segure um halter acima da cabeça com as duas mãos, desça atrás da cabeça.', 'Halter', true),
('Mergulho no Banco', 'Tríceps', ARRAY['Ombro', 'Peito'], 'Mãos no banco atrás, pernas estendidas, desça e empurre com os tríceps.', 'Peso Corporal', true),
('Tríceps Coice com Halter', 'Tríceps', ARRAY[], 'Inclinado, cotovelo fixo, estenda o antebraço para trás contraindo o tríceps.', 'Halter', true),
('Tríceps no Cabo com Corda', 'Tríceps', ARRAY[], 'Polia alta com corda, separe as pontas ao final do movimento para maior contração.', 'Cabo', true),
('Fundos entre Barras', 'Tríceps', ARRAY['Peito', 'Ombro'], 'Apoiado nas barras paralelas, desça e empurre mantendo o tronco levemente inclinado.', 'Peso Corporal', true),
('Tríceps na Máquina', 'Tríceps', ARRAY[], 'Sentado na máquina, empurre as alças para baixo estendendo os cotovelos.', 'Máquina', true),
('Tríceps Testa com Halter', 'Tríceps', ARRAY[], 'Deite no banco, desça os halteres até a testa dobrando os cotovelos e empurre.', 'Halter', true),

-- ANTEBRAÇO (6 exercícios)
('Rosca de Punho com Barra', 'Antebraço', ARRAY[], 'Sentado, antebraços apoiados nas coxas, flexione os punhos segurando a barra.', 'Barra', true),
('Rosca Inversa de Punho', 'Antebraço', ARRAY[], 'Mesma posição com pegada pronada, estenda os punhos para trabalhar o extensor.', 'Barra', true),
('Farmer Walk', 'Antebraço', ARRAY['Trapézio', 'Ombro'], 'Segure halteres pesados e caminhe por uma distância determinada.', 'Halter', true),
('Hang from Bar', 'Antebraço', ARRAY['Costas'], 'Pendurado na barra estática, segure pelo tempo máximo possível.', 'Peso Corporal', true),
('Rosca de Punho com Cabo', 'Antebraço', ARRAY[], 'Polia baixa, antebraço apoiado, flexione e estenda o punho.', 'Cabo', true),
('Plate Pinch', 'Antebraço', ARRAY[], 'Segure um anilho liso com os dedos e polegar pelo maior tempo possível.', 'Outro', true),

-- QUADRÍCEPS (12 exercícios)
('Agachamento com Barra', 'Quadríceps', ARRAY['Glúteos', 'Lombar', 'Posterior de Coxa'], 'Barra nos trapézios, pés na largura dos ombros, desça até as coxas paralelas e suba.', 'Barra', true),
('Leg Press 45°', 'Quadríceps', ARRAY['Glúteos', 'Posterior de Coxa'], 'Sentado na máquina, pés na plataforma, desça controlado e empurre sem travar os joelhos.', 'Máquina', true),
('Cadeira Extensora', 'Quadríceps', ARRAY[], 'Sentado na máquina, estenda as pernas até o topo contraindo o quadríceps.', 'Máquina', true),
('Agachamento Goblet', 'Quadríceps', ARRAY['Glúteos'], 'Segure o kettlebell ou halter no peito, agache profundo mantendo o tronco ereto.', 'Kettlebell', true),
('Afundo com Halteres', 'Quadríceps', ARRAY['Glúteos', 'Posterior de Coxa'], 'Passo à frente, desça o joelho traseiro até próximo do chão e volte.', 'Halter', true),
('Agachamento Búlgaro', 'Quadríceps', ARRAY['Glúteos', 'Posterior de Coxa'], 'Pé traseiro elevado no banco, desça o joelho em direção ao chão e suba.', 'Halter', true),
('Agachamento Hack', 'Quadríceps', ARRAY['Glúteos'], 'Na máquina hack, pés baixos na plataforma, desça profundo e empurre.', 'Máquina', true),
('Agachamento Sumô', 'Quadríceps', ARRAY['Glúteos', 'Posterior de Coxa', 'Panturrilha'], 'Pés abertos com pontas para fora, barra nos trapézios, agache profundo.', 'Barra', true),
('Step-Up com Halter', 'Quadríceps', ARRAY['Glúteos'], 'Suba um degrau ou banco com um halter em cada mão alternando as pernas.', 'Halter', true),
('Agachamento no Smith', 'Quadríceps', ARRAY['Glúteos', 'Lombar'], 'Barra do Smith nos trapézios, pés levemente à frente, agache controlado.', 'Smith', true),
('Agachamento Livre', 'Quadríceps', ARRAY['Glúteos'], 'Pés na largura dos ombros, braços à frente, desça até as coxas paralelas e suba.', 'Peso Corporal', true),
('Leg Press Horizontal', 'Quadríceps', ARRAY['Glúteos', 'Posterior de Coxa'], 'Deitado na máquina horizontal, empurre a plataforma sem travar os joelhos.', 'Máquina', true),

-- POSTERIOR DE COXA (10 exercícios)
('Cadeira Flexora', 'Posterior de Coxa', ARRAY['Glúteos'], 'Deitado ou sentado na máquina, flexione os joelhos contraindo os isquiotibiais.', 'Máquina', true),
('Stiff com Barra', 'Posterior de Coxa', ARRAY['Glúteos', 'Lombar'], 'Em pé com a barra, incline o tronco à frente mantendo as pernas semiflexionadas.', 'Barra', true),
('Stiff com Halter', 'Posterior de Coxa', ARRAY['Glúteos', 'Lombar'], 'Mesmo movimento do stiff com barra, usando halteres.', 'Halter', true),
('Good Morning', 'Posterior de Coxa', ARRAY['Lombar', 'Glúteos'], 'Barra nos trapézios, incline o tronco à frente com joelhos semi-flexionados.', 'Barra', true),
('Levantamento Terra Romeno', 'Posterior de Coxa', ARRAY['Glúteos', 'Lombar'], 'Barra na frente das coxas, desça mantendo a barra próxima ao corpo e lombar neutra.', 'Barra', true),
('Flexora no Cabo', 'Posterior de Coxa', ARRAY['Glúteos'], 'De pé com o cabo na tornozeira, flexione o joelho contraindo o posterior.', 'Cabo', true),
('Curl Nórdico', 'Posterior de Coxa', ARRAY[], 'Joelhos no chão com pés fixos, desça lentamente para frente usando o posterior de coxa.', 'Peso Corporal', true),
('Ponte com Halter', 'Posterior de Coxa', ARRAY['Glúteos'], 'Deitado, pés apoiados, halter no quadril, eleve o quadril contraindo glúteos e isquiotibiais.', 'Halter', true),
('Leg Curl Sentado', 'Posterior de Coxa', ARRAY[], 'Sentado na máquina, flexione os joelhos puxando as almofadas para baixo.', 'Máquina', true),
('Hiperextensão no Banco', 'Posterior de Coxa', ARRAY['Lombar', 'Glúteos'], 'Apoiado no banco romano, desça o tronco e suba contraindo o posterior e lombar.', 'Peso Corporal', true),

-- GLÚTEOS (10 exercícios)
('Agachamento Profundo', 'Glúteos', ARRAY['Quadríceps', 'Posterior de Coxa'], 'Agache abaixo do paralelo com a barra para maximizar o recrutamento dos glúteos.', 'Barra', true),
('Hip Thrust com Barra', 'Glúteos', ARRAY['Posterior de Coxa'], 'Costas no banco, barra no quadril, empurre o quadril para cima contraindo os glúteos.', 'Barra', true),
('Glúteo no Cabo', 'Glúteos', ARRAY['Posterior de Coxa'], 'Tornozeira no cabo baixo, chute para trás com a perna estendida contraindo o glúteo.', 'Cabo', true),
('Abdução no Cabo', 'Glúteos', ARRAY[], 'Tornozeira no cabo baixo, leve a perna para o lado contraindo o glúteo médio.', 'Cabo', true),
('Abdutora na Máquina', 'Glúteos', ARRAY[], 'Sentado na máquina, empurre as coxas para fora contra a resistência.', 'Máquina', true),
('Glúteo no Banco', 'Glúteos', ARRAY['Posterior de Coxa'], 'Em quatro apoios, estenda uma perna para trás e para cima contraindo o glúteo.', 'Peso Corporal', true),
('Afundo Reverso', 'Glúteos', ARRAY['Quadríceps', 'Posterior de Coxa'], 'Passo para trás, desça o joelho até próximo do chão enfatizando o glúteo.', 'Halter', true),
('Passada Lateral', 'Glúteos', ARRAY['Quadríceps'], 'Passo largo para o lado, desça o quadril e empurre de volta contraindo o glúteo.', 'Peso Corporal', true),
('Hip Thrust no Smith', 'Glúteos', ARRAY['Posterior de Coxa'], 'Costas no banco com a barra do Smith no quadril, empurre para cima.', 'Smith', true),
('Agachamento com Elástico', 'Glúteos', ARRAY['Quadríceps'], 'Elástico acima dos joelhos, agache empurrando os joelhos para fora contra o elástico.', 'Elástico', true),

-- PANTURRILHA (8 exercícios)
('Panturrilha em Pé na Máquina', 'Panturrilha', ARRAY[], 'Em pé na máquina, eleve os calcanhares ao máximo e desça controlado.', 'Máquina', true),
('Panturrilha Sentado na Máquina', 'Panturrilha', ARRAY[], 'Sentado com almofadas nos joelhos, eleve os calcanhares contraindo a panturrilha.', 'Máquina', true),
('Gêmeo com Barra', 'Panturrilha', ARRAY[], 'Barra nos trapézios, suba na ponta dos pés em uma superfície elevada.', 'Barra', true),
('Panturrilha Unilateral', 'Panturrilha', ARRAY[], 'Apoiado em uma superfície, suba na ponta de um pé por vez segurando um halter.', 'Halter', true),
('Panturrilha no Leg Press', 'Panturrilha', ARRAY[], 'No leg press, empurre a plataforma com as pontas dos pés estendendo os tornozelos.', 'Máquina', true),
('Panturrilha no Degrau', 'Panturrilha', ARRAY[], 'Calcanhar além do degrau, eleve ao máximo e desça além do nível do degrau.', 'Peso Corporal', true),
('Jump Rope', 'Panturrilha', ARRAY['Quadríceps'], 'Pule a corda apoiando nas pontas dos pés, mantendo ritmo constante.', 'Outro', true),
('Panturrilha com Kettlebell', 'Panturrilha', ARRAY[], 'Em pé segurando o kettlebell, suba nas pontas dos pés de forma controlada.', 'Kettlebell', true),

-- ABDÔMEN (12 exercícios)
('Abdominal Crunch', 'Abdômen', ARRAY[], 'Deitado com joelhos dobrados, eleve os ombros do chão contraindo o abdômen.', 'Peso Corporal', true),
('Prancha Isométrica', 'Abdômen', ARRAY['Lombar', 'Ombro'], 'Apoiado nos antebraços e pontas dos pés, mantenha o corpo reto pelo tempo determinado.', 'Peso Corporal', true),
('Abdominal Infra', 'Abdômen', ARRAY[], 'Deitado, eleve as pernas estendidas ou semiflexionadas até 90° e desça controlado.', 'Peso Corporal', true),
('Bicicleta Abdominal', 'Abdômen', ARRAY[], 'Deitado, simule a pedalada alternando cotovelo e joelho opostos.', 'Peso Corporal', true),
('Crunch no Cabo', 'Abdômen', ARRAY[], 'Ajoelhado na polia alta, puxe a corda contraindo o abdômen em direção aos joelhos.', 'Cabo', true),
('Russian Twist', 'Abdômen', ARRAY[], 'Sentado com tronco inclinado, gire o tronco de lado a lado segurando um peso.', 'Halter', true),
('Hollow Body', 'Abdômen', ARRAY[], 'Deitado, braços acima da cabeça, eleve levemente pernas e ombros mantendo a posição.', 'Peso Corporal', true),
('Dead Bug', 'Abdômen', ARRAY['Lombar'], 'Deitado, braços ao teto, abaixe o braço e perna opostos de forma coordenada.', 'Peso Corporal', true),
('Abdominal Oblíquo', 'Abdômen', ARRAY[], 'Deitado, leve o cotovelo em direção ao joelho oposto alternando os lados.', 'Peso Corporal', true),
('Wheel Rollout', 'Abdômen', ARRAY['Lombar', 'Ombro'], 'Ajoelhado com a roda abdominal, role para frente mantendo o core contraído.', 'Outro', true),
('Hanging Leg Raise', 'Abdômen', ARRAY['Quadríceps'], 'Pendurado na barra, eleve as pernas até 90° ou até tocar a barra.', 'Peso Corporal', true),
('Sit-Up Completo', 'Abdômen', ARRAY['Quadríceps'], 'Deitado com pés fixos, suba o tronco completamente e desça controlado.', 'Peso Corporal', true),

-- TRAPÉZIO (8 exercícios)
('Encolhimento com Barra', 'Trapézio', ARRAY['Ombro'], 'Em pé com a barra na frente, eleve os ombros em direção às orelhas e desça.', 'Barra', true),
('Encolhimento com Halter', 'Trapézio', ARRAY['Ombro'], 'Em pé com halteres nas laterais, eleve os ombros contraindo o trapézio.', 'Halter', true),
('Encolhimento no Cabo', 'Trapézio', ARRAY['Ombro'], 'Polia baixa, eleve os ombros puxando o cabo para cima.', 'Cabo', true),
('Remada Alta', 'Trapézio', ARRAY['Ombro', 'Bíceps'], 'Barra na frente, cotovelos para cima e fora, puxe até a altura do queixo.', 'Barra', true),
('Encolhimento Atrás', 'Trapézio', ARRAY['Ombro'], 'Barra atrás do corpo, eleve os ombros em direção às orelhas.', 'Barra', true),
('Face Pull com Corda', 'Trapézio', ARRAY['Ombro'], 'Polia alta com corda, puxe em direção ao rosto com cotovelos elevados.', 'Cabo', true),
('Encolhimento no Smith', 'Trapézio', ARRAY['Ombro'], 'Barra do Smith na frente ou atrás, eleve os ombros de forma controlada.', 'Smith', true),
('Farmers Walk Pesado', 'Trapézio', ARRAY['Antebraço', 'Ombro'], 'Carregue halteres muito pesados caminhando para ativar isometricamente o trapézio.', 'Halter', true),

-- LOMBAR (8 exercícios)
('Hiperextensão no Roman Chair', 'Lombar', ARRAY['Glúteos', 'Posterior de Coxa'], 'Apoiado no banco romano, desça o tronco e suba mantendo a lombar contraída.', 'Peso Corporal', true),
('Hiperextensão com Peso', 'Lombar', ARRAY['Glúteos', 'Posterior de Coxa'], 'Mesmo movimento da hiperextensão segurando um peso no peito.', 'Halter', true),
('Superman', 'Lombar', ARRAY['Glúteos'], 'Deitado de barriga para baixo, eleve braços e pernas simultaneamente.', 'Peso Corporal', true),
('Bird Dog', 'Lombar', ARRAY['Abdômen'], 'Em quatro apoios, estenda o braço e perna opostos mantendo a coluna neutra.', 'Peso Corporal', true),
('Levantamento Terra', 'Lombar', ARRAY['Costas', 'Glúteos', 'Quadríceps', 'Trapézio'], 'Puxe a barra do chão mantendo a coluna neutra até ficar completamente em pé.', 'Barra', true),
('Back Extension no Cabo', 'Lombar', ARRAY['Glúteos'], 'Polia baixa, inclinado à frente, suba o tronco contraindo a lombar.', 'Cabo', true),
('Prancha Lateral', 'Lombar', ARRAY['Abdômen'], 'Apoiado no antebraço e lateral do pé, mantenha o corpo reto lateralmente.', 'Peso Corporal', true),
('Good Morning com Barra', 'Lombar', ARRAY['Posterior de Coxa', 'Glúteos'], 'Barra nos trapézios, incline o tronco mantendo as costas retas e joelhos semiflexionados.', 'Barra', true);
